In [1]:
from scipy.stats import norm
import biogeme.biogeme as bio
from biogeme.expressions import Beta, Variable, bioDraws, MonteCarlo, exp, log, Elem, bioNormalCdf
from biogeme import models
from biogeme.models import ordered_probit, ordered_logit
from biogeme import results as res
from biogeme.results import compile_estimation_results, calcPValue
import pandas as pd
import biogeme.database as db
import numpy as np
import biogeme.distributions as dist
import pickle
from urllib.request import urlopen
import os

In [2]:
df=pd.read_csv('final_dataset copie.csv')

C:\Users\martin.dejaeghere\AppData\Local\Temp\7\ipykernel_36104\1150838593.py:1: DtypeWarning: Columns (16,50,51,55,56,65,67,69,77,84,85,86,87,88,89,118) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('final_dataset copie.csv')

## Sanity check

In [3]:
df['Gender_driver'] = df['Gender_driver'].astype(str)
df['Helmet_driver'] = df['Helmet_driver'].astype(str)

In [4]:
df=df[df['severity']!=-1]

In [5]:
df=df.loc[df['Vehicle'].isin(['E-scooter','Bike','E-bike','Pedestrian'])]

In [6]:
# Remplacer les NaN par une nouvelle catégorie
df['Road width'] = df['Road width'].fillna('Missing')
df['age_2'] = df['age_2'].fillna(0)
df['Maneuver_2'] = df['Maneuver_2'].fillna('Missing')

In [7]:
df['plan']=df['plan'].astype(str)

In [8]:
df_dummies=pd.get_dummies(df[['Crossroad','Helmet','Point of impact','Gender','vehicle_type_2','Vehicle','Pavement','tram','Intersection'
                              , 'User category', 'Lighting conditions', 'Cycle facilities', 'Road width', 'Agglomeration', 'Age category',
                              'Accident location', 'Surface condition', 'Maneuver', 'Maneuver_2','Gender_2', 'Pedestrian localisation', 'Pedestrian action', 'Vehicle_2',
'Max speed', 'Long profile', 'Weather conditions', 'Road type', 'Trip purpose','Reflective jacket', 'plan','Point of impact_2', 'Obstacle','Gender_driver','Helmet_driver','age_driver','Year', 'Maneuver_3','Point of impact_3','Gender_3','Vehicle_3'

]])
df_dummies = df_dummies.astype(int)  # Convert boolean to integers

In [9]:
# Select columns that are not of type object
df_non_dummies = df[['age','severity','Number of passengers','number of involved vehicles','vma','largeurcha','pentemoyen','largeurtro','age_2','catu', 'Num_Acc','age_opposite_mean']]

In [10]:
df_non_dummies=pd.concat([df_non_dummies,df_dummies],axis=1)
df_non_dummies['road segment']=df_non_dummies['Crossroad_No intersection']

In [11]:
df_non_dummies=df_non_dummies.dropna(subset=['age','severity'])

In [12]:
df_non_dummies = df_non_dummies.reset_index(drop=True)

In [13]:
df_non_dummies['largeurcha'] = df_non_dummies['largeurcha'].fillna(999)
df_non_dummies['largeurtro'] = df_non_dummies['largeurtro'].fillna(999)
df_non_dummies['pentemoyen'] = df_non_dummies['pentemoyen'].fillna(999)
df_non_dummies['age_opposite_mean'] = df_non_dummies['age_opposite_mean'].fillna(999)

In [14]:
df_escooter=df_non_dummies.loc[df_non_dummies['Vehicle_E-scooter']==1]
df_ebike=df_non_dummies.loc[df_non_dummies['Vehicle_E-bike']==1]
df_bike=df_non_dummies.loc[df_non_dummies['Vehicle_Bike']==1]

In [15]:
df_carcrashes=df_non_dummies.loc[(df_non_dummies['vehicle_type_2_Cars']==1) | (df_non_dummies['vehicle_type_2_Large motorized vehicle'] ==1) | (df_non_dummies['vehicle_type_2_Light motorized vehicle']==1) ]
df_mmv=df_non_dummies.loc[(df_non_dummies['vehicle_type_2_Micromobility vehicle']==1) ]
df_alone=df_non_dummies.loc[df_non_dummies['vehicle_type_2_No other vehcile']==1]

df_carcrashes=df_carcrashes.loc[df_carcrashes['catu'].isin([1,2])]
df_mmv=df_mmv.loc[df_mmv['catu'].isin([1,2])]
df_mmv=df_mmv.loc[df_mmv['severity']!=3]
df_alone=df_alone.loc[df_alone['catu'].isin([1,2])]

num_acc_values = df_non_dummies.loc[df_non_dummies['vehicle_type_2_Pedestrian'] == 1, 'Num_Acc']

# Step 2: Filter the DataFrame to include rows with those Num_Acc values
df_pedestrian = df_non_dummies[df_non_dummies['Num_Acc'].isin(num_acc_values)]



df_carcrashes_escooter=df_escooter.loc[(df_escooter['vehicle_type_2_Cars']==1) | (df_escooter['vehicle_type_2_Large motorized vehicle'] ==1) | (df_escooter['vehicle_type_2_Light motorized vehicle']==1)]
df_carcrashes_ebike=df_ebike.loc[(df_ebike['vehicle_type_2_Cars']==1) | (df_ebike['vehicle_type_2_Large motorized vehicle'] ==1) | (df_ebike['vehicle_type_2_Light motorized vehicle']==1)]
df_carcrashes_bike=df_bike.loc[(df_bike['vehicle_type_2_Cars']==1) | (df_bike['vehicle_type_2_Large motorized vehicle'] ==1) | (df_bike['vehicle_type_2_Light motorized vehicle']==1)]

In [16]:
database_carcrashes = db.Database('database_carcrashes', df_carcrashes)
database_mmv= db.Database('database_mmv',df_mmv)
database_pedestrian= db.Database('database_pedestrian',df_pedestrian)
database_alone= db.Database('database_alone',df_alone)
database= db.Database('database',df_non_dummies)
database_carcrashes_escooter = db.Database('database_carcrashes_escooter', df_carcrashes_escooter)
database_carcrashes_ebike = db.Database('database_carcrashes_ebike', df_carcrashes_ebike)
database_carcrashes_bike = db.Database('database_carcrashes_bike', df_carcrashes_bike)

## Variables

In [17]:
age_020=Variable('Age category_0-20')
age_4160=Variable('Age category_41-60')
age_61=Variable('Age category_61+')
age=Variable('age')
age_opposite_mean=Variable('age_opposite_mean')
severity=Variable('severity')
Gender_Male=Variable('Gender_Male')
Gender_Female=Variable('Gender_Female')
Helmet=Variable('Helmet_Yes')
inv_car=Variable('Involved vehicle 1_Car')
Crossroad_no_traffic_lights=Variable('Crossroad_No traffic lights')
Crossroad_Traffic_lights=Variable('Crossroad_Traffic lights')
Crossroad_Roundabout=Variable('Crossroad_Roundabouts')
passengers=Variable('Number of passengers')
nb_involved_vehi=Variable('number of involved vehicles')
vma=Variable('vma')
e_scooter=Variable('Vehicle_E-scooter')
bike=Variable('Vehicle_Bike')
ebike=Variable('Vehicle_E-bike')
vehicle_car=Variable('Vehicle_Car')
e_scooter_2=Variable('Vehicle_2_E-scooter')
bike_2=Variable('Vehicle_2_Bike')
ebike_2=Variable('Vehicle_2_E-bike')
e_scooter_3=Variable('Vehicle_3_E-scooter')
bike_3=Variable('Vehicle_3_Bike')
ebike_3=Variable('Vehicle_3_E-bike')

e_car_2=Variable('Vehicle_2_Car')
heavy_motorized=Variable('vehicle_type_2_Large motorized vehicle')
light_motorized=Variable('vehicle_type_2_Light motorized vehicle')
light_non_motorized=Variable('Involved vehicle 1 type_Light non-motorized vehicle')
no_other_vehicle=Variable('Involved vehicle 1 type_No other vehicle')
inv_pedestrian=Variable('Involved vehicle 1 type_Pedestrian')
back=Variable('Point of impact_Back')
left=Variable('Point of impact_Left side')
right=Variable('Point of impact_Right side')

back_opposite=Variable('Point of impact_opposite_Back')
left_opposite=Variable('Point of impact_opposite_Left side')
right_opposite=Variable('Point of impact_opposite_Right side')


no_int=Variable('Intersection_No intersection')
paved=Variable('Pavement_Paved')
roadwidth1012m=Variable('Road width_10-12 m')
roadwidth46m=Variable('Road width_4-6 m')	
roadwidth68m=Variable('Road width_6-8 m')	
roadwidth810m=Variable('Road width_8-10 m')	
roadwidth4m=Variable('Road width_<4 m')
roadwidth12m=Variable('Road width_> 12m')
roadwidth_missing=Variable('Road width_Missing')
driver=Variable('User category_Driver')
passenger=Variable('User category_Passenger')
pedestrian=Variable('User category_Pedestrian')
lyon= Variable('Agglomeration_MÉTROPOLE DE LYON')
paris= Variable('Agglomeration_MÉTROPOLE DU GRAND PARIS')

night_light=Variable('Lighting conditions_Night with street lightings on')
night=Variable('Lighting conditions_Night without street lightings')
twilight=Variable('Lighting conditions_Twilight')
daylight=Variable('Lighting conditions_Daylight')

roadwidth=Variable('largeurcha')

morning_peak=Variable('Time of day_Morning peak hours')
afternoon_peak=Variable('Time of day_Afternoon peak hours')

road_segment=Variable('road segment')
pentemoyen=Variable('pentemoyen')
largeurtro=Variable('largeurtro')
female_opposite=Variable('Gender_2_Female')
female_opposite_3=Variable('Gender_3_Female')

on_cycle=Variable('Accident location_On cycle facility')
on_special_way=Variable('Accident location_On other special way')
on_sidewalk=Variable('Accident location_On sidewalk')
on_road=Variable('Accident location_On road')

Intersection_Cross=Variable('Intersection_Cross intersection')
Intersection_T=Variable('Intersection_T intersection')
Intersection_Square=Variable('Intersection_Square')
Intersection_Y=Variable('Intersection_Y intersection')

# Déclaration des variables
cycle_facilities_bus_lane = Variable('Cycle facilities_Bus lane')
cycle_facilities_cycle_lane = Variable('Cycle facilities_Cycle lane')
cycle_facilities_cycle_path_greenway = Variable('Cycle facilities_Cycle path/Greenway')
cycle_facilities_no_cycle_facilities = Variable('Cycle facilities_No cycle facilities')
cycle_facilities_pedestrianized_street = Variable('Cycle facilities_Pedestrianized street')
cycle_facilities_two_way_cycle = Variable('Cycle facilities_Two-way cycle')

# Déclaration des variables
tram_on_tracks = Variable('tram_On tracks')
tram_tram_crossing = Variable('tram_Tram crossing')

wet=Variable('Surface condition_Wet')

# Déclaration des variables
maneuver_crossing_road = Variable('Maneuver_Crossing the road')
maneuver_deported = Variable('Maneuver_Deported')
maneuver_opposite_direction = Variable('Maneuver_In the opposite direction')
maneuver_other = Variable('Maneuver_Other')
maneuver_overtaking = Variable('Maneuver_Overtaking')
maneuver_turning_left = Variable('Maneuver_Turning left')
maneuver_turning_right = Variable('Maneuver_Turning right')

maneuver_without_change_direction = Variable('Maneuver_Without change of direction')

age_involved=Variable('age_2')
maneuver_crossing_road_involved = Variable('Maneuver_2_Crossing the road')
maneuver_deported_involved = Variable('Maneuver_2_Deported')
maneuver_opposite_direction_involved = Variable('Maneuver_2_In the opposite direction')
maneuver_other_involved = Variable('Maneuver_2_Other')
maneuver_overtaking_involved = Variable('Maneuver_2_Overtaking')
maneuver_turning_involved_right = Variable('Maneuver_2_Turning left')
maneuver_turning_involved_left = Variable('Maneuver_2_Turning right')
maneuver_involved_parked = Variable('Maneuver_2_Parked')

age_involved_3=Variable('age_3')
age_opposite_mean_var = Variable('age_opposite_mean')

maneuver_crossing_road_involved_3 = Variable('Maneuver_3_Crossing the road')
maneuver_deported_involved_3= Variable('Maneuver_3_Deported')
maneuver_opposite_direction_involved_3 = Variable('Maneuver_3_In the opposite direction')
maneuver_other_involved_3 = Variable('Maneuver_3_Other')
maneuver_overtaking_involved_3 = Variable('Maneuver_3_Overtaking')
maneuver_turning_involved_right_3 = Variable('Maneuver_3_Turning left')
maneuver_turning_involved_left_3 = Variable('Maneuver_3_Turning right')
maneuver_involved_parked_3 = Variable('Maneuver_3_Parked')

poteau=Variable('Obstacle_Poteau')
bordure=Variable('Obstacle_Sidewalk bordure')
parked_vehi=Variable('Obstacle_Parked_vehicle')


maneuver_without_change_direction_involved = Variable('Maneuver_2_Without change of direction')
maneuver_door_opening_involved = Variable('Maneuver_2_Door opening')

vehicle_type_2_Cars=Variable('vehicle_type_2_Cars')
vehicle_type_2_Large_motorized_vehicle= Variable('vehicle_type_2_Large motorized vehicle')
vehicle_type_2_Light_motorized_vehicle=Variable('vehicle_type_2_Light motorized vehicle')
vehicle_type_2_Micromobility_vehicle=Variable('vehicle_type_2_Micromobility vehicle')
vehicle_type_2_Pedestrian=Variable('vehicle_type_2_Pedestrian')
no_other_vehicle=Variable('vehicle_type_2_No other vehicle')

pedestrian_crossing=Variable('Pedestrian action_Crossing')
pedestrian_moving=Variable('Pedestrian action_Moving')

MaxSpeed_20=Variable('Max speed_20 km/h')
MaxSpeed_30=Variable('Max speed_30 km/h')
MaxSpeed_50=Variable('Max speed_50 km/h')
MaxSpeed_10=Variable('Max speed_< 10 km/h')

pedestrian_on_crossing=Variable('Pedestrian localisation_On a pedestrian crossing')
pedestrian_on_road=Variable('Pedestrian localisation_On the road')
pedestrian_on_sidewalk=Variable('Pedestrian localisation_On sidewalk')

slope=Variable('Long profile_Slope')

normal_weather=Variable('Weather conditions_Normal')
cloudy_weather=Variable('Weather conditions_Cloudy / Fog')
rainy_weather=Variable('Weather conditions_Rain / Snow')

cycleway=Variable('Road type_Cycleway')
path=Variable('Road type_Path')
pedestrian_area=Variable('Road type_Pedestrian area')
primary=Variable('Road type_Primary')
residential=Variable('Road type_Residential')
secondary=Variable('Road type_Secondary')
tertiary=Variable('Road type_Tertiary')

leisure=Variable('Trip purpose_Leisure/Shopping')
jacket_yes=Variable('Reflective jacket_Yes')
prof_use=Variable('Trip purpose_Professional use')

plan_2=Variable('plan_2')
plan_3=Variable('plan_3')

Helmet_driver_Yes=Variable('Helmet_driver_Yes')
Gender_driver_Female=Variable('Gender_driver_Female')
Age_driver=Variable('age_driver')

## Definition of the Betas

In [18]:
constant_2 = Beta('constant_2', 0, None, None, 0)
constant_3 = Beta('constant_3', 0, None, None, 0)
constant_4 = Beta('constant_4', 0, None, None, 0)

Beta_female = Beta('Beta Female', 0, None, None, 0)
Beta_female_2=Beta('Beta Female 2', 0, None, None, 0)
Beta_female_3=Beta('Beta Female 3', 0, None, None, 0)
Beta_female_4=Beta('Beta Female 4', 0, None, None, 0)

Beta_age_020_2 = Beta('Beta_age_020_2', 0, None, None, 0)
Beta_age_020_3 = Beta('Beta_age_020_3', 0, None, None, 0)
Beta_age_020_4 = Beta('Beta_age_020_4', 0, None, None, 0)
Beta_age_61_2 = Beta('Beta_age_61_2', 0, None, None, 0)
Beta_age_61_3 = Beta('Beta_age_61_3', 0, None, None, 0)
Beta_age_61_4 = Beta('Beta_age_61_4', 0, None, None, 0)
Beta_age_4160_2 = Beta('Beta_age_4160_2', 0, None, None, 0)
Beta_age_4160_3 = Beta('Beta_age_4160_3', 0, None, None, 0)
Beta_age_4160_4 = Beta('Beta_age_4160_4', 0, None, None, 0)
Beta_age_020 = Beta('Beta_age_020', 0, None, None, 0)
Beta_age_61 = Beta('Beta_age_61', 0, None, None, 0)
Beta_age_4160 = Beta('Beta_age_4160', 0, None, None, 0)

Beta_age_2= Beta('Beta_age_2', 0, None, None, 0)
Beta_age_3= Beta('Beta_age_3', 0, None, None, 0)
Beta_age_4= Beta('Beta_age_4', 0, None, None, 0)
Beta_age= Beta('Beta_age', 0, None, None, 0)


Beta_helmet=Beta('Beta_helmet', 0, None, None, 0)
Beta_helmet_2=Beta('Beta_helmet 2', 0, None, None, 0)
Beta_helmet_3=Beta('Beta_helmet 3', 0, None, None, 0)
Beta_helmet_4=Beta('Beta_helmet 4', 0, None, None, 0)

Beta_helmet_ebike=Beta('Beta_helmet_ebike', 0, None, None, 0)
Beta_helmet_escooter=Beta('Beta_helmet_escooter', 0, None, None, 0)

Beta_vma=Beta('Beta_vma',0,None,None,0)
Beta_vma_2=Beta('Beta_vma_2',0,None,None,0)
Beta_vma_3=Beta('Beta_vma_3',0,None,None,0)
Beta_vma_4=Beta('Beta_vma_4',0,None,None,0)


Beta_ebike_2=Beta('Beta_ebike 2',0,None,None,0)
Beta_escooter_2=Beta('Beta_escooter 2',0,None,None,0)
Beta_ebike_3=Beta('Beta_ebike 3',0,None,None,0)
Beta_escooter_3=Beta('Beta_escooter 3',0,None,None,0)
Beta_ebike_4=Beta('Beta_ebike 4',0,None,None,0)
Beta_escooter_4=Beta('Beta_escooter 4',0,None,None,0)

Beta_ebike_2_opposite=Beta('Beta_ebike 2_opposite',0,None,None,0)
Beta_escooter_2_opposite=Beta('Beta_escooter 2_opposite',0,None,None,0)
Beta_ebike_3_opposite=Beta('Beta_ebike 3_opposite',0,None,None,0)
Beta_escooter_3_opposite=Beta('Beta_escooter 3_opposite',0,None,None,0)
Beta_ebike_4_opposite=Beta('Beta_ebike 4_opposite',0,None,None,0)
Beta_escooter_4_opposite=Beta('Beta_escooter 4_opposite',0,None,None,0)

Beta_crossroad_traffic_lights=Beta('Beta_crossroad_traffic_lights', 0, None, None, 0)
Beta_crossroad_roundabout=Beta('Beta_crossroad_roundabout', 0, None, None, 0)

Beta_crossroad_traffic_lights_2=Beta('Beta_crossroad_traffic_lights 2', 0, None, None, 0)
Beta_crossroad_roundabout_2=Beta('Beta_crossroad_roundabout 2', 0, None, None, 0)
Beta_crossroad_traffic_lights_3=Beta('Beta_crossroad_traffic_lights 3', 0, None, None, 0)
Beta_crossroad_roundabout_3=Beta('Beta_crossroad_roundabout 3', 0, None, None, 0)
Beta_crossroad_traffic_lights_4=Beta('Beta_crossroad_traffic_lights 4', 0, None, None, 0)
Beta_crossroad_roundabout_4=Beta('Beta_crossroad_roundabout 4', 0, None, None, 0)
Beta_crossroad_no_traffic_lights_2=Beta('Beta_crossroad_no_traffic_lights 2', 0, None, None, 0)
Beta_crossroad_no_traffic_lights_3=Beta('Beta_crossroad_no_traffic_lights 3', 0, None, None, 0)
Beta_crossroad_no_traffic_lights_4=Beta('Beta_crossroad_no_traffic_lights 4', 0, None, None, 0)

Beta_passengers=Beta('Beta_passengers', 0, None, None, 0)
Beta_passengers_2=Beta('Beta_passengers 2', 0, None, None, 0)
Beta_passengers_3=Beta('Beta_passengers 3', 0, None, None, 0)
Beta_passengers_4=Beta('Beta_passengers 4', 0, None, None, 0)

Beta_nb_involved_vehi=Beta('Beta_nb_involved_vehi', 0, None, None, 0)
Beta_nb_involved_vehi_2=Beta('Beta_nb_involved_vehi 2', 0, None, None, 0)
Beta_nb_involved_vehi_3=Beta('Beta_nb_involved_vehi 3', 0, None, None, 0)
Beta_nb_involved_vehi_4=Beta('Beta_nb_involved_vehi 4', 0, None, None, 0)

Beta_involved_vehicle_car=Beta('Beta_involved_vehicle_car', 0, None, None, 0)

Beta_light_motorized=Beta('Beta Involved vehicle 1 type_Light motorized vehicle', 0, None, None, 0)
Beta_light_non_motorized=Beta('Beta Involved vehicle 1 type_Light non-motorized vehicle', 0, None, None, 0)
Beta_no_other_vehicle=Beta('Beta Involved vehicle 1 type_No other vehicle', 0, None, None, 0)
Beta_inv_pedestrian=Beta('Beta Involved vehicle 1 type_Pedestrian', 0, None, None, 0)

Beta_back=Beta('Beta Point of impact_Back', 0, None, None, 0)

Beta_back_2=Beta('Beta Point of impact_Back 2', 0, None, None, 0)
Beta_back_3=Beta('Beta Point of impact_Back 3', 0, None, None, 0)
Beta_back_4=Beta('Beta Point of impact_Back 4', 0, None, None, 0)

Beta_left=Beta('Beta Point of impact_Left', 0, None, None, 0)
Beta_right=Beta('Beta Point of impact_Right', 0, None, None, 0)

Beta_left_2=Beta('Beta Point of impact_Left 2', 0, None, None, 0)
Beta_right_2=Beta('Beta Point of impact_Right 2', 0, None, None, 0)
Beta_left_3=Beta('Beta Point of impact_Left 3', 0, None, None, 0)
Beta_right_3=Beta('Beta Point of impact_Right 3', 0, None, None, 0)
Beta_left_4=Beta('Beta Point of impact_Left 4', 0, None, None, 0)
Beta_right_4=Beta('Beta Point of impact_Right 4', 0, None, None, 0)

Beta_opposite_back_2=Beta('Beta Point of impact_opposite_Back 2', 0, None, None, 0)
Beta_opposite_back_3=Beta('Beta Point of impact_opposite_Back 3', 0, None, None, 0)
Beta_opposite_back_4=Beta('Beta Point of impact_opposite_Back 4', 0, None, None, 0)



Beta_left_opposite_2=Beta('Beta Point of impact_opposite_Left 2', 0, None, None, 0)
Beta_right_opposite_2=Beta('Beta Point of impact_opposite_Right 2', 0, None, None, 0)
Beta_left_opposite_3=Beta('Beta Point of impact_opposite_Left 3', 0, None, None, 0)
Beta_right_opposite_3=Beta('Beta Point of impact_opposite_Right 3', 0, None, None, 0)
Beta_lef_oppositet_4=Beta('Beta Point of impact_opposite_Left 4', 0, None, None, 0)
Beta_right_opposite_4=Beta('Beta Point of impact_opposite_Right 4', 0, None, None, 0)


Beta_paved_2=Beta('Beta Paved 2',0, None, None, 0)
Beta_paved_3=Beta('Beta Paved 3',0, None, None, 0)
Beta_paved_4=Beta('Beta Paved 4',0, None, None, 0)
Beta_paved=Beta('Beta Paved',0, None, None, 0)


Beta_pedestrian=Beta('Beta User category_Pedestrian 2',0, None, None, 0)
Beta_pedestrian_2=Beta('Beta User category_Pedestrian 2',0, None, None, 0)
Beta_pedestrian_3=Beta('Beta User category_Pedestrian 3',0, None, None, 0)
Beta_pedestrian_4=Beta('Beta User category_Pedestrian 4',0, None, None, 0)

Beta_lyon= Beta('Beta Lyon', 0, None, None, 0 )

Beta_daylight_2=Beta('Beta Lighting conditions_Daylight 2',0, None, None, 0)
Beta_daylight_3=Beta('Beta Lighting conditions_Daylight 3',0, None, None, 0)
Beta_daylight_4=Beta('Beta Lighting conditions_Daylight 4',0, None, None, 0)

Beta_night_light_2=Beta('Beta Lighting conditions_Night with street lightings on 2',0, None, None, 0)
Beta_night_2=Beta('Beta Lighting conditions_Night without street lightings 2',0, None, None, 0)
Beta_twilight_2=Beta('Beta Lighting conditions_Twilight 2',0, None, None, 0)

Beta_night_light_3=Beta('Beta Lighting conditions_Night with street lightings on 3',0, None, None, 0)
Beta_night_3=Beta('Beta Lighting conditions_Night without street lightings 3',0, None, None, 0)
Beta_twilight_3=Beta('Beta Lighting conditions_Twilight 3',0, None, None, 0)

Beta_night_light_4=Beta('Beta Lighting conditions_Night with street lightings on 4',0, None, None, 0)
Beta_night_4=Beta('Beta Lighting conditions_Night without street lightings 4',0, None, None, 0)
Beta_twilight_4=Beta('Beta Lighting conditions_Twilight 4',0, None, None, 0)


Beta_night_light=Beta('Beta Lighting conditions_Night with street lightings on ',0, None, None, 0)
Beta_night=Beta('Beta Lighting conditions_Night without street lightings ',0, None, None, 0)
Beta_twilight=Beta('Beta Lighting conditions_Twilight',0, None, None, 0)

Beta_afternoon_peak_2=Beta('Beta Time of day_Afternoon peak hours 2',0, None, None, 0)
Beta_morning_peak_2=Beta('Beta Time of day_Morning peak hours 2',0, None, None, 0)

Beta_afternoon_peak_3=Beta('Beta Time of day_Afternoon peak hours 3',0, None, None, 0)
Beta_morning_peak_3=Beta('Beta Time of day_Morning peak hours 3',0, None, None, 0)

Beta_afternoon_peak_4=Beta('Beta Time of day_Afternoon peak hours 4',0, None, None, 0)
Beta_morning_peak_4=Beta('Beta Time of day_Morning peak hours 4',0, None, None, 0)

Beta_afternoon_peak=Beta('Beta Time of day_Afternoon peak hours',0, None, None, 0)

Beta_pentemoyen=Beta('Beta pentemoyen',0, None, None, 0)
Beta_pentemoyen_2=Beta('Beta pentemoyen 2',0, None, None, 0)
Beta_pentemoyen_3=Beta('Beta pentemoyen 3',0, None, None, 0)
Beta_pentemoyen_4=Beta('Beta pentemoyen 4',0, None, None, 0)

Beta_largeurtro_2=Beta('Beta largeurtro_2',0, None, None, 0)
Beta_largeurtro_3=Beta('Beta largeurtro_3',0, None, None, 0)
Beta_largeurtro_4=Beta('Beta largeurtro_4',0, None, None, 0)


Beta_on_cycle=Beta('Beta Accident location_On cycle facility ',0, None, None, 0)
Beta_on_special_way=Beta('Beta Accident location_On other special way ',0, None, None, 0)
Beta_on_sidewalk=Beta('Beta Accident location_On sidewalk ',0, None, None, 0)

Beta_on_road_2=Beta('Beta Accident location_On road 2',0, None, None, 0)
Beta_on_cycle_2=Beta('Beta Accident location_On cycle facility 2',0, None, None, 0)
Beta_on_special_way_2=Beta('Beta Accident location_On other special way 2',0, None, None, 0)
Beta_on_sidewalk_2=Beta('Beta Accident location_On sidewalk 2',0, None, None, 0)

Beta_on_road_3=Beta('Beta Accident location_On road 3',0, None, None, 0)
Beta_on_cycle_3=Beta('Beta Accident location_On cycle facility 3',0, None, None, 0)
Beta_on_special_way_3=Beta('Beta Accident location_On other special way 3',0, None, None, 0)
Beta_on_sidewalk_3=Beta('Beta Accident location_On sidewalk 3',0, None, None, 0)

Beta_on_road_4=Beta('Beta Accident location_On road 4',0, None, None, 0)
Beta_on_cycle_4=Beta('Beta Accident location_On cycle facility 4',0, None, None, 0)
Beta_on_special_way_4=Beta('Beta Accident location_On other special way 4',0, None, None, 0)
Beta_on_sidewalk_4=Beta('Beta Accident location_On sidewalk 4',0, None, None, 0)


Beta_Intersection_Cross=Beta('Beta_Intersection_Cross intersection 2',0, None, None, 0)
Beta_Intersection_T_2=Beta('Beta_Intersection_T intersection 2',0, None, None, 0)
Beta_Intersection_Square_2=Beta('Beta_Intersection_Square 2',0, None, None, 0)
Beta_Intersection_Y_2=Beta('Beta_Intersection_Y intersection 2',0, None, None, 0)
Beta_no_int_2=Beta('Beta Intersection_No intersection', 0, None, None, 0)

Beta_Intersection_Cross_3=Beta('Beta_Intersection_Cross intersection 3',0, None, None, 0)
Beta_Intersection_T_3=Beta('Beta_Intersection_T intersection 3',0, None, None, 0)
Beta_Intersection_Square_3=Beta('Beta_Intersection_Square 3',0, None, None, 0)
Beta_Intersection_Y_3=Beta('Beta_Intersection_Y intersection 3',0, None, None, 0)
Beta_no_int_3=Beta('Beta Intersection_No intersection 3', 0, None, None, 0)

Beta_Intersection_Cross_4=Beta('Beta_Intersection_Cross intersection 4',0, None, None, 0)
Beta_Intersection_T_4=Beta('Beta_Intersection_T intersection 4',0, None, None, 0)
Beta_Intersection_Square_4=Beta('Beta_Intersection_Square 4',0, None, None, 0)
Beta_Intersection_Y_4=Beta('Beta_Intersection_Y intersection 4',0, None, None, 0)
Beta_no_int_4=Beta('Beta Intersection_No intersection 4', 0, None, None, 0)

Beta_bus_lane_ = Beta('Beta_bus_lane ', 0, None, None, 0)
Beta_cycle_lane = Beta('Beta_cycle_lane', 0, None, None, 0)
Beta_cycle_path_greenway = Beta('Beta_cycle_path_greenway', 0, None, None, 0)
Beta_no_cycle_facilities = Beta('Beta_no_cycle_facilities', 0, None, None, 0)
Beta_pedestrianized_street = Beta('Beta_pedestrianized_street', 0, None, None, 0)
Beta_two_way_cycle = Beta('Beta_two_way_cycle', 0, None, None, 0)

Beta_bus_lane_2 = Beta('Beta_bus_lane 2', 0, None, None, 0)
Beta_cycle_lane_2 = Beta('Beta_cycle_lane 2', 0, None, None, 0)
Beta_cycle_path_greenway_2 = Beta('Beta_cycle_path_greenway 2', 0, None, None, 0)
Beta_bus_lane_3 = Beta('Beta_bus_lane 3', 0, None, None, 0)
Beta_cycle_lane_3 = Beta('Beta_cycle_lane 3', 0, None, None, 0)
Beta_cycle_path_greenway_3 = Beta('Beta_cycle_path_greenway 3', 0, None, None, 0)
Beta_bus_lane_4 = Beta('Beta_bus_lane 4', 0, None, None, 0)
Beta_cycle_lane_4 = Beta('Beta_cycle_lane 4', 0, None, None, 0)
Beta_cycle_path_greenway_4 = Beta('Beta_cycle_path_greenway 4', 0, None, None, 0)

Beta_wet_2=Beta('Beta Surface condition_Wet 2', 0, None, None, 0)
Beta_wet_3=Beta('Beta Surface condition_Wet 3', 0, None, None, 0)


# Déclaration des bêtas pour chaque suffixe
Beta_crossing_road_2 = Beta('Beta_crossing_road_2', 0, None, None, 0)
Beta_deported_2 = Beta('Beta_deported_2', 0, None, None, 0)
Beta_opposite_direction_2 = Beta('Beta_opposite_direction_2', 0, None, None, 0)
Beta_other_2 = Beta('Beta_other_2', 0, None, None, 0)
Beta_overtaking_2 = Beta('Beta_overtaking_2', 0, None, None, 0)
Beta_turning_left_2 = Beta('Beta_turning_left_2', 0, None, None, 0)
Beta_turning_right_2 = Beta('Beta_turning_right_2', 0, None, None, 0)
Beta_parked_2 = Beta('Beta_parked_2', 0, None, None, 0)


Beta_without_change_direction_2_bike = Beta('Beta_without_change_direction_2_bike', 0, None, None, 0)
Beta_without_change_direction_2_escoot = Beta('Beta_without_change_direction_2_escoot', 0, None, None, 0)

Beta_door_opening_2 = Beta('Beta_door_opening_2', 0, None, None, 0)

Beta_crossing_road_3 = Beta('Beta_crossing_road_3', 0, None, None, 0)
Beta_deported_3 = Beta('Beta_deported_3', 0, None, None, 0)
Beta_opposite_direction_3 = Beta('Beta_opposite_direction_3', 0, None, None, 0)
Beta_other_3 = Beta('Beta_other_3', 0, None, None, 0)
Beta_overtaking_3 = Beta('Beta_overtaking_3', 0, None, None, 0)
Beta_turning_left_3 = Beta('Beta_turning_left_3', 0, None, None, 0)
Beta_turning_right_3 = Beta('Beta_turning_right_3', 0, None, None, 0)

Beta_without_change_direction_3 = Beta('Beta_without_change_direction_3', 0, None, None, 0)
Beta_door_opening_3 = Beta('Beta_door_opening_3', 0, None, None, 0)

Beta_crossing_road_4 = Beta('Beta_crossing_road_4', 0, None, None, 0)
Beta_deported_4 = Beta('Beta_deported_4', 0, None, None, 0)
Beta_opposite_direction_4 = Beta('Beta_opposite_direction_4', 0, None, None, 0)
Beta_other_4 = Beta('Beta_other_4', 0, None, None, 0)
Beta_overtaking_4 = Beta('Beta_overtaking_4', 0, None, None, 0)
Beta_turning_left_4 = Beta('Beta_turning_left_4', 0, None, None, 0)
Beta_turning_right_4 = Beta('Beta_turning_right_4', 0, None, None, 0)

Beta_without_change_direction_4 = Beta('Beta_without_change_direction_4', 0, None, None, 0)
Beta_door_opening_4 = Beta('Beta_door_opening_4', 0, None, None, 0)


Beta_crossing_road_involved_2 = Beta('Beta_crossing_road_involved_2', 0, None, None, 0)
Beta_deported_involved_2 = Beta('Beta_deported_involved_2', 0, None, None, 0)
Beta_opposite_direction_involved_2 = Beta('Beta_opposite_direction_involved_2', 0, None, None, 0)
Beta_other_involved_2 = Beta('Beta_other_involved_2', 0, None, None, 0)
Beta_overtaking_involved_2 = Beta('Beta_overtaking_involved_2', 0, None, None, 0)
Beta_turning_right_involved_2 = Beta('Beta_turning_right_involved_2', 0, None, None, 0)
Beta_turning_left_involved_2 = Beta('Beta_turning_left_involved_2', 0, None, None, 0)

Beta_without_change_direction_involved_2 = Beta('Beta_without_change_direction_involved_2', 0, None, None, 0)

Beta_crossing_road_involved_3 = Beta('Beta_crossing_road_involved_3', 0, None, None, 0)
Beta_deported_involved_3 = Beta('Beta_deported_involved_3', 0, None, None, 0)
Beta_opposite_direction_involved_3 = Beta('Beta_opposite_direction_involved_3', 0, None, None, 0)
Beta_other_involved_3 = Beta('Beta_other_involved_3', 0, None, None, 0)
Beta_overtaking_involved_3 = Beta('Beta_overtaking_involved_3', 0, None, None, 0)
Beta_turning_right_involved_3 = Beta('Beta_turning_right_involved_3', 0, None, None, 0)
Beta_turning_left_involved_3 = Beta('Beta_turning_left_involved_3', 0, None, None, 0)

Beta_without_change_direction_involved_3 = Beta('Beta_without_change_direction_involved_3', 0, None, None, 0)

Beta_crossing_road_involved_4 = Beta('Beta_crossing_road_involved_4', 0, None, None, 0)
Beta_deported_involved_4 = Beta('Beta_deported_involved_4', 0, None, None, 0)
Beta_opposite_direction_involved_4 = Beta('Beta_opposite_direction_involved_4', 0, None, None, 0)
Beta_other_involved_4 = Beta('Beta_other_involved_4', 0, None, None, 0)
Beta_overtaking_involved_4 = Beta('Beta_overtaking_involved_4', 0, None, None, 0)
Beta_turning_right_involved_4 = Beta('Beta_turning_right_involved_4', 0, None, None, 0)
Beta_turning_left_involved_4 = Beta('Beta_turning_left_involved_4', 0, None, None, 0)

Beta_without_change_direction_involved_4 = Beta('Beta_without_change_direction_involved_4', 0, None, None, 0)

Beta_age_involved_2=Beta('Beta_age_involved_2', 0, None, None, 0)
Beta_age_involved_3=Beta('Beta_age_involved_3', 0, None, None, 0)
Beta_age_involved_4=Beta('Beta_age_involved_4', 0, None, None, 0)

Beta_slope_2=Beta('Beta_slope_2', 0, None, None, 0)
Beta_slope_3=Beta('Beta_slope_3', 0, None, None, 0)
Beta_slope_4=Beta('Beta_slope_4', 0, None, None, 0)

In [19]:
Beta_Cars_2 = Beta('Beta_Cars_2', 0, None, None, 0)   # Beta for level 2 (Cars)
Beta_Cars_3 = Beta('Beta_Cars_3', 0, None, None, 0)   # Beta for level 3 (Cars)
Beta_Cars_4 = Beta('Beta_Cars_4', 0, None, None, 0)   # Beta for level 4 (Cars)
Beta_Cars = Beta('Beta_Cars', 0, None, None, 0)   # Beta for level 4 (Cars)

Beta_Large_2 = Beta('Beta_Large_2', 0, None, None, 0)  # Beta for level 2 (Large motorized vehicle)
Beta_Large_3 = Beta('Beta_Large_3', 0, None, None, 0)  # Beta for level 3 (Large motorized vehicle)
Beta_Large_4 = Beta('Beta_Large_4', 0, None, None, 0)  # Beta for level 4 (Large motorized vehicle)
Beta_Large = Beta('Beta_Large', 0, None, None, 0)  # Beta for level 4 (Large motorized vehicle)

Beta_Light_2 = Beta('Beta_Light_2', 0, None, None, 0)  # Beta for level 2 (Light motorized vehicle)
Beta_Light_3 = Beta('Beta_Light_3', 0, None, None, 0)  # Beta for level 3 (Light motorized vehicle)
Beta_Light_4 = Beta('Beta_Light_4', 0, None, None, 0)  # Beta for level 4 (Light motorized vehicle)
Beta_Light = Beta('Beta_Light', 0, None, None, 0)  # Beta for level 4 (Light motorized vehicle)

Beta_Micromobility_2 = Beta('Beta_Micromobility_2', 0, None, None, 0)  # Beta for level 2 (Micromobility vehicle)
Beta_Micromobility_3 = Beta('Beta_Micromobility_3', 0, None, None, 0)  # Beta for level 3 (Micromobility vehicle)
Beta_Micromobility_4 = Beta('Beta_Micromobility_4', 0, None, None, 0)  # Beta for level 4 (Micromobility vehicle)
Beta_Micromobility = Beta('Beta_Micromobility', 0, None, None, 0)  # Beta for level 4 (Micromobility vehicle)

Beta_Pedestrian_2 = Beta('Beta_Pedestrian_2', 0, None, None, 0)  # Beta for level 2 (Pedestrian)
Beta_Pedestrian_3 = Beta('Beta_Pedestrian_3', 0, None, None, 0)  # Beta for level 3 (Pedestrian)
Beta_Pedestrian_4 = Beta('Beta_Pedestrian_4', 0, None, None, 0)  # Beta for level 4 (Pedestrian)
Beta_Pedestrian = Beta('Beta_Pedestrian', 0, None, None, 0)  # Beta for level 4 (Pedestrian)

Beta_no_other_vehicle_2=Beta('Beta_No other vehicle 2', 0, None, None, 0)
Beta_no_other_vehicle_3=Beta('Beta_No other vehicle 3', 0, None, None, 0)
Beta_no_other_vehicle_4=Beta('Beta_No other vehicle 4', 0, None, None, 0)
Beta_no_other_vehicle=Beta('Beta_No other vehicle ', 0, None, None, 0)

Beta_female_opposite_2=Beta('Gender_2_Female 2', 0, None, None, 0)
Beta_female_opposite_3=Beta('Gender_2_Female 3', 0, None, None, 0)
Beta_female_opposite_4=Beta('Gender_2_Female 4', 0, None, None, 0)

Beta_Helmet_driver_Yes=Beta('Beta_Helmet_driver_Yes', 0, None, None, 0)
Beta_Gender_driver_Female=Beta('Beta_Gender_driver_Female', 0, None, None, 0)
Beta_Age_driver=Beta('Beta_Age_driver', 0, None, None, 0)

Beta_age_involved_2_car=Beta('Beta_age_involved_2_car',0,None,None,0)
Beta_age_involved_2_light=Beta('Beta_age_involved_2_light',0,None,None,0)
Beta_age_involved_4_car=Beta('Beta_age_involved_4_car',0,None,None,0)
Beta_age_involved_4_light=Beta('Beta_age_involved_4_light',0,None,None,0)

Beta_heavy_2_car=Beta('Beta_heavy_2_car',0,None,None,0)
Beta_light_2=Beta('Beta_light_2',0,None,None,0)
Beta_heavy_4_car=Beta('Beta_heavy_4_car',0,None,None,0)
Beta_light_4=Beta('Beta_light_4',0,None,None,0)

Beta_jacket=Beta('Beta_jacket',0,None,None,0)
Beta_back_bike_2=Beta('Beta_back_bike_2',0,None,None,0)
Beta_overtaking_involved_bike_2=Beta('Beta_overtaking_involved_bike_2',0,None,None,0)
Beta_back_e_scooter=Beta('Beta_back_e_scooter_2',0,None,None,0)

## Model for car crashes

In [20]:
V1 = 0

V2 = (  Beta_female_2 * Gender_Female  + constant_2 
      + Beta_passengers_2*passenger + Beta_nb_involved_vehi_2*nb_involved_vehi
     + Beta_back_bike_2*back*(bike+ebike) + Beta_back_e_scooter*back*e_scooter
 + Beta_light_2*light_motorized
+Beta_overtaking_involved_2*maneuver_overtaking_involved
 + Beta_without_change_direction_2_bike * maneuver_without_change_direction*bike  
   + passenger*( Beta_Gender_driver_Female*Gender_driver_Female )
+ Beta_no_int_2*no_int
)

V3 =  (  constant_4 
        + Beta_passengers_2*passenger 
       + Beta_age_4*age
 + Beta_vma_4*vma*no_int 
 + Beta_heavy_4_car*heavy_motorized + Beta_light_4*light_motorized
+ Beta_daylight_4*daylight
               +Beta_turning_left_involved_4*maneuver_turning_involved_left
              + Beta_on_cycle_4*on_cycle  + Beta_jacket*jacket_yes*night +   Beta_night*night
                + passenger*( Beta_Gender_driver_Female*Gender_driver_Female )
 )



# Create dictionary of utility functions
V_carcrashes = {
    1: V1,
    2: V2,
    3: V3
}

In [21]:
availability = {
    1: 1, 
    2: 1, 
    3: 1   
}

In [22]:

U={1:0,2:constant_2,3:constant_3}

model_name = 'InitialModel_carcrashes'


logprob = models.loglogit(U, availability, severity)

# Créez l'objet Biogeme
model_cst_car = bio.BIOGEME(database_carcrashes, logprob)
model_cst_car.modelName = model_name

# Estimation


results_constant_car = model_cst_car.estimate()

In [26]:
# Random-parameters
sigma_2 = Beta('sigma 2', 0, None, None, 0)

X1 = bioDraws('X1', 'NORMAL')


# Adding the error component to the utilities
V1c=0
V2c = V_carcrashes[2]+ sigma_2*X1
V3c = V_carcrashes[3]

V_carcrashes_mixed={1:V1c,2:V2c,3:V3c}

prob = models.logit(V_carcrashes_mixed,availability,severity)


# We integrate over B_TIME_RND using Monte-Carlo
logprob = log(MonteCarlo(prob))



# Create the Biogeme object
model_car  = bio.BIOGEME(database_carcrashes,logprob,number_of_draws=10000)
model_car.modelName = "random_parameter_logit_car_crashes"

# Estimate the parameters. 
results_ml_carcrashes = model_car.estimate()

In [45]:
results_ml_carcrashes.get_estimated_parameters()

,Value,Rob. Std err,Rob. t-test,Rob. p-value
Beta Accident location_On cycle facility 4,-1.028449,0.516858,-1.989810,4.661188e-02
Beta Female 2,0.804336,0.176765,4.550319,5.356458e-06
Beta Intersection_No intersection,0.470238,0.177007,2.656603,7.893232e-03
Beta Lighting conditions_Daylight 4,-0.905489,0.324700,-2.788695,5.292093e-03
Beta Lighting conditions_Night without street lightings,1.811776,0.726109,2.495185,1.258914e-02
Beta_Gender_driver_Female,-1.108684,0.551468,-2.010424,4.438638e-02
Beta_age_4,0.041357,0.010553,3.918895,8.895579e-05
Beta_back_bike_2,-0.372052,0.218439,-1.703232,8.852460e-02
Beta_back_e_scooter_2,-1.024530,0.397288,-2.578807,9.914221e-03
Beta_heavy_4_car,2.973395,0.330052,9.008867,0.000000e+00
Beta_jacket,-3.165765,0.933097,-3.392751,6.919447e-04
Beta_light_2,-2.924258,0.268698,-10.883078,0.000000e+00
Beta_light_4,-3.981620,0.977379,-4.073772,4.625782e-05
Beta_nb_involved_vehi 2,-1.793215,0.322601,-5.558621,2.719146e-08
Beta_overtaking_involved_2,-0.546522,0.282452,-1.934917,5.300051e-02
Beta_passengers 2,-2.855991,0.404001,-7.069262,1.557643e-12
Beta_turning_left_involved_4,1.140857,0.353328,3.228894,1.242700e-03
Beta_vma_4,0.015792,0.007933,1.990688,4.651523e-02
Beta_without_change_direction_2_bike,0.647746,0.175190,3.697388,2.178290e-04
constant_2,8.849632,0.989246,8.945839,0.000000e+00
constant_4,-2.502470,0.526475,-4.753252,2.001703e-06
sigma 2,-1.766375,0.325713,-5.423104,5.857290e-08

## MMV

In [27]:
Beta_bike=Beta('Beta_bike',0,None,None,0)
Beta_bike_2=Beta('Beta_bike_2',0,None,None,0)
Beta_ebike=Beta('Beta_ebike',0,None,None,0)
Beta_age_involved_2_epmd=Beta('Beta_age_involved_2_epmd',0,None,None,0)
Beta_age_involved_2_bike=Beta('Beta_age_involved_2_bike',0,None,None,0)

Beta_back_bike=Beta('Beta_back_bike',0,None,None,0)

In [28]:


V1 = 0


V2 = (  Beta_female_2 * Gender_Female  + constant_2 

+ Beta_female_opposite_2*(female_opposite+female_opposite_3)
     + Beta_back_bike*back *(bike+ebike)  
    + Beta_back*back*e_scooter+ Beta_wet_2*wet+
Beta_age*age
+ Beta_deported_2*maneuver_deported+ Beta_turning_left_2*(maneuver_turning_left)
+Beta_age_involved_2_epmd*(age_opposite_mean_var)
 + Beta_escooter_2_opposite*(e_scooter_2+ e_scooter_3)
)

# Dictionnaire des fonctions d'utilité
V_mmv = {
    1: V1,
    2: V2,
}

In [29]:
availability1={1:1,2:1}

model_name = 'logit_mmv'

# Fichiers à écraser

logprob_2 = models.loglogit(V_mmv, availability1, severity)
model_mmv = bio.BIOGEME(database_mmv, logprob_2)
model_mmv.modelName = model_name
results_logit_mmv= model_mmv.estimate()
results_logit_mmv.get_estimated_parameters()

,Value,Rob. Std err,Rob. t-test,Rob. p-value
Beta Female 2,1.087872,0.169854,6.404733,1.506333e-10
Beta Point of impact_Back,1.233340,0.662627,1.861289,6.270342e-02
Beta Surface condition_Wet 2,-0.583028,0.231229,-2.521432,1.168784e-02
Beta_age,0.035325,0.005307,6.655710,2.819367e-11
Beta_age_involved_2_epmd,-0.033901,0.004345,-7.802728,5.995204e-15
Beta_back_bike,-1.142539,0.220417,-5.183528,2.177281e-07
Beta_deported_2,-0.500938,0.194589,-2.574342,1.004308e-02
Beta_escooter 2_opposite,-0.308722,0.171967,-1.795235,7.261619e-02
Beta_turning_left_2,-1.235408,0.316112,-3.908140,9.300959e-05
Gender_2_Female 2,-1.114450,0.144545,-7.710032,1.265654e-14
constant_2,1.010076,0.252457,4.000987,6.307881e-05

In [30]:
V1m=0
V2m = constant_2


U={1:V1m,2:V2m}

In [31]:
model_name = 'InitialModel_mmv'



logprob_2 = models.loglogit(U, availability1, severity)

# Créez l'objet Biogeme
model_cst_mmv = bio.BIOGEME(database_mmv, logprob_2)
model_cst_mmv.modelName = model_name

# Estimation


results_constant_mmv = model_cst_mmv.estimate()

## Pedestrian

In [32]:
Beta_age_bike_4=Beta('Beta_age_bike_4',0,None,None,0)

In [33]:
utility_pedestrian = (Beta_female* Gender_Female  
       + Beta_age_bike_4*age      
       + Beta_no_int_2*no_int 
          + (Beta_age_involved_2 * age_involved)*(nb_involved_vehi==2) + Beta_female_opposite_2*female_opposite*(nb_involved_vehi==2)
   + Beta_pedestrian*pedestrian + Beta_turning_left_involved_2*pedestrian*(maneuver_turning_involved_left+maneuver_turning_involved_right)*(nb_involved_vehi==2)
            +Beta_crossroad_traffic_lights_2*Crossroad_Traffic_lights 
)

In [34]:
model_name = 'ordinal_probit_pedestrian'

tau_1 = Beta('tau_1', 1, None, None, 0)
   
# :math:`\tau_2 = \tau_2 + \delta_2`
the_proba = ordered_probit(
    continuous_value=utility_pedestrian,
    list_of_discrete_values=[1, 2, 3],
    tau_parameter=tau_1,
)

the_chosen_proba = Elem(the_proba, severity)

logprob = log((the_chosen_proba))
model_pedes = bio.BIOGEME(database_pedestrian, logprob)
model_pedes.modelName = model_name
results_pedes = model_pedes.estimate()
results_pedes.get_estimated_parameters()

,Value,Rob. Std err,Rob. t-test,Rob. p-value
Beta Female,0.516042,0.066935,7.709628,1.265654e-14
Beta Intersection_No intersection,0.244234,0.068624,3.559019,3.722426e-04
Beta User category_Pedestrian 2,1.346991,0.071884,18.738298,0.000000e+00
Beta_age_bike_4,0.014931,0.001612,9.260657,0.000000e+00
Beta_age_involved_2,-0.007405,0.001449,-5.111394,3.197902e-07
Beta_crossroad_traffic_lights 2,0.227235,0.078058,2.911108,3.601500e-03
Beta_turning_left_involved_2,0.529640,0.110501,4.793076,1.642435e-06
Gender_2_Female 2,-0.568743,0.065118,-8.734005,0.000000e+00
tau_1,0.791052,0.105418,7.503937,6.195044e-14
tau_1_diff_2,4.173085,0.170846,24.426004,0.000000e+00

In [35]:
model_name = 'ordinal_probit_pedestrian_init'

tau_1 = Beta('tau_1', 1, None, None, 0)
   
# :math:`\tau_2 = \tau_2 + \delta_2`
the_proba = ordered_probit(
    continuous_value=0,
    list_of_discrete_values=[1, 2, 3],
    tau_parameter=tau_1,
)

the_chosen_proba = Elem(the_proba, severity)

logprob = log((the_chosen_proba))
model_cst_pedes = bio.BIOGEME(database_pedestrian, logprob)
model_cst_pedes.modelName = model_name
results_pedes_cst = model_cst_pedes.estimate()

## Single-vehicle

In [36]:
Beta_age_bike = Beta('Beta_age_bike_mean', 0, None, None, 0)



Beta_age_e_bike = Beta('Beta_age_e_bike_mean', 0, None, None, 0)

Beta_age_e_scooter_mean = Beta('Beta_age_e_scooter_mean', 0, None, None, 0)
Beta_age_e_scooter_s = Beta('Beta_age_e_scooter_s', 0, None, None, 0)
Beta_age_e_scooter_mixed = Beta_age_e_scooter_mean + Beta_age_e_scooter_s * bioDraws('Beta_age_e_scooter_random', 'NORMAL')

Beta_passengers_2_mean_mixed = Beta('Beta_passengers_2_mean', 0, None, None, 0)
Beta_passengers_2_s_mixed = Beta('Beta_passengers_2_s', 0, None, None, 0)
Beta_passengers_2_mixed = Beta_passengers_2_mean_mixed + Beta_passengers_2_s_mixed * bioDraws('Beta_passengers_2_random_mixed', 'NORMAL')

Beta_slope_2 = Beta('Beta_slope_2_mean', 0, None, None, 0)
Beta_helmet_mean = Beta('Beta_helmet_mean', 0, None, None, 0)
Beta_helmet_s = Beta('Beta_helmet_s', 0, None, None, 0)
Beta_helmet_mixed = Beta_helmet_mean + Beta_helmet_s * bioDraws('Beta_helmet_random', 'NORMAL')

Beta_vma_s = Beta('Beta_vma_s', 0, None, None, 0)
Beta_vma_mean = Beta('Beta_vma_mean', 0, None, None, 0)
Beta_vma_mixed = Beta_vma_mean + Beta_vma_s * bioDraws('Beta_vma_random', 'NORMAL')
Beta_jacket_2=Beta('Beta_jacket_2',0,None,None,0)
Beta_jacket = Beta('Beta_jacket', 0, None, None, 0)
Beta_bike = Beta('Beta_bike', 0, None, None, 0)
Beta_jacket_mean = Beta('Beta_helmet_mean', 0, None, None, 0)
Beta_jacket_s = Beta('Beta_jacket_s', 0, None, None, 0)
Beta_jacket_mixed = Beta_jacket_mean + Beta_jacket_s * bioDraws('Beta_jacket_mean', 'NORMAL')
Beta_slope_1=Beta('Beta_slope_1', 0, None, None, 0)


utility_sv = (
    Beta_age * age  +
    Beta_passengers_2_mixed* passenger 
+ Beta_slope_1*slope 
+Beta_helmet_ebike*Helmet*ebike
+ Beta_passengers_4*driver*(passengers==1) 
)

In [37]:
model_name = 'ordered_probit_sinv'

tau_1 = Beta('tau_1', 1, None, None, 0)
   
# :math:`\tau_2 = \tau_2 + \delta_2`
the_proba = ordered_probit(
    continuous_value=utility_sv,
    list_of_discrete_values=[1, 2, 3],
    tau_parameter=tau_1,
)

the_chosen_proba = Elem(the_proba, severity)

logprob = log(MonteCarlo(the_chosen_proba))
model_solo_2 = bio.BIOGEME(database_alone, logprob,number_of_draws=10000)
model_solo_2.modelName = model_name
results_solo_2 = model_solo_2.estimate()
results_solo_2.get_estimated_parameters()

                           Value  Rob. Std err  Rob. t-test  Rob. p-value
Beta_age                0.010171      0.003847     2.643982      0.008194
Beta_helmet_ebike      -0.321902      0.171616    -1.875714      0.060695
Beta_passengers 4      -2.357647      0.251282    -9.382488      0.000000
Beta_passengers_2_mean -1.568838      0.335342    -4.678320      0.000003
Beta_passengers_2_s     1.558927      0.320005     4.871570      0.000001
Beta_slope_1            0.312374      0.172809     1.807627      0.070665
tau_1                  -2.594701      0.220059   -11.790952      0.000000
tau_1_diff_2            5.355331      0.211125    25.365745      0.000000

In [38]:
model_name = 'ordered_logit_s_init'

tau_1 = Beta('tau_1', 1, None, None, 0)
   
# :math:`\tau_2 = \tau_2 + \delta_2`
the_proba = ordered_probit(
    continuous_value=0,
    list_of_discrete_values=[1, 2, 3],
    tau_parameter=tau_1,
)

the_chosen_proba = Elem(the_proba, severity)

logprob = log((the_chosen_proba))
model_cst_solo = bio.BIOGEME(database_alone, logprob)
model_cst_solo.modelName = model_name
results_cst_solo = model_cst_solo.estimate()
results_cst_solo.get_estimated_parameters()

                 Value  Rob. Std err  Rob. t-test  Rob. p-value
tau_1        -2.115696      0.064929   -32.584718           0.0
tau_1_diff_2  4.395508      0.099081    44.362708           0.0

## Likelihood-ratio test

In [39]:
def get_results(file_path):

    # Ouvrir le fichier en mode binaire
    with open(file_path, 'rb') as file:
        data = pickle.load(file)

    result = res.bioResults(data)
    
    # Retourner le résultat
    return result


#res_restricted=get_results('logit_mmv~51.pickle')
#res_unrestricted=get_results('panel_mmv~36.pickle')

#res_restricted.likelihood_ratio_test(res_unrestricted, 0.01)

## Out-of sample validation of the models

In [40]:
# Create DataFrames for each year and without each year
years = [2019, 2020, 2021, 2022, 2023]

# Classe pour contenir les données de validation
class ValidationData:
    def __init__(self, estimation, validation):
        self.estimation = estimation
        self.validation = validation

def create_validation_data(df):
    validation_data=[]
    validation_data.append(ValidationData(df[df['Year'].isin([2019, 2020, 2021, 2022])], df[df['Year'] == 2023]))
    df_lyon = df[df['Agglomeration_MÉTROPOLE DE LYON'] == 1]
    df_paris = df[df['Agglomeration_MÉTROPOLE DU GRAND PARIS']==1]
    validation_data.append(ValidationData(df_paris, df_lyon))
    return validation_data



# Create validation data for each dataset
validationData_car = create_validation_data(df_carcrashes)
validationData_mmv= create_validation_data(df_mmv)
validationData_alone_2 = create_validation_data(df_alone)
validationData_pedestrian = create_validation_data(df_pedestrian)

In [41]:
# Validate the model with the validation data for mmv
validation_results_car = model_car.validate(results_ml_carcrashes, validationData_car)
validation_results_car_cst = model_cst_car.validate(results_ml_carcrashes, validationData_car)


# Initialize variables to store log-likelihoods
loglike_model_mmv = 0
loglike_constant_mmv = 0
loglike_model_car = 0
loglike_constant_car = 0

# Calculate log-likelihood for the model (mmv)
for i, slide in enumerate(validation_results_car):
    validation_loglike = slide['Loglikelihood'].sum()
    loglike_model_mmv += validation_loglike
    print(
        f'Log likelihood for {slide.shape[0]} validation data on car (slide {i+1}): '
        f'{validation_loglike}'
    )

# Calculate log-likelihood for the constant model (mmv)
for i, slide in enumerate(validation_results_car_cst):
    validation_loglike_cst = slide['Loglikelihood'].sum()
    loglike_constant_mmv += validation_loglike_cst
    print(
        f'Log likelihood for {slide.shape[0]} validation data on car (constant model, slide {i+1}): '
        f'{validation_loglike_cst}'
    )

# Calculate rho-square for each slide (mmv)
for i in range(len(validation_results_car)):
    validation_loglike = validation_results_car[i]['Loglikelihood'].sum()
    validation_loglike_cst = validation_results_car_cst[i]['Loglikelihood'].sum()
    rho_square = 1 - (validation_loglike / validation_loglike_cst)
    print(f'Rho-square for the validation data on car (slide {i+1}): {rho_square}')

Log likelihood for 2129 validation data on car (slide 1): -346.9276297181166
Log likelihood for 1361 validation data on car (slide 2): -217.3674699591931
Log likelihood for 2129 validation data on car (constant model, slide 1): -400.53398591750596
Log likelihood for 1361 validation data on car (constant model, slide 2): -249.84584173136724
Rho-square for the validation data on car (slide 1): 0.1338372225183162
Rho-square for the validation data on car (slide 2): 0.12999364546997216

In [42]:
# Validate the model with the validation data for mmv
validation_results_mmv = model_mmv.validate(results_logit_mmv, validationData_mmv)
validation_results_mmv_cst = model_cst_mmv.validate(results_constant_mmv, validationData_mmv)


# Initialize variables to store log-likelihoods
loglike_model_mmv = 0
loglike_constant_mmv = 0
loglike_model_car = 0
loglike_constant_car = 0

# Calculate log-likelihood for the model (mmv)
for i, slide in enumerate(validation_results_mmv):
    validation_loglike = slide['Loglikelihood'].sum()
    loglike_model_mmv += validation_loglike
    print(
        f'Log likelihood for {slide.shape[0]} validation data on mmv (slide {i+1}): '
        f'{validation_loglike}'
    )

# Calculate log-likelihood for the constant model (mmv)
for i, slide in enumerate(validation_results_mmv_cst):
    validation_loglike_cst = slide['Loglikelihood'].sum()
    loglike_constant_mmv += validation_loglike_cst
    print(
        f'Log likelihood for {slide.shape[0]} validation data on mmv (constant model, slide {i+1}): '
        f'{validation_loglike_cst}'
    )

# Calculate rho-square for each slide (mmv)
for i in range(len(validation_results_mmv)):
    validation_loglike = validation_results_mmv[i]['Loglikelihood'].sum()
    validation_loglike_cst = validation_results_mmv_cst[i]['Loglikelihood'].sum()
    rho_square = 1 - (validation_loglike / validation_loglike_cst)
    print(f'Rho-square for the validation data on mmv (slide {i+1}): {rho_square}')

Log likelihood for 374 validation data on mmv (slide 1): -191.92290758603764
Log likelihood for 87 validation data on mmv (slide 2): -41.85734706285469
Log likelihood for 374 validation data on mmv (constant model, slide 1): -237.10399490357747
Log likelihood for 87 validation data on mmv (constant model, slide 2): -53.451666575303506
Rho-square for the validation data on mmv (slide 1): 0.19055388474544055
Rho-square for the validation data on mmv (slide 2): 0.21691221724797982

In [43]:

# Validate the model with the validation data for mmv
validation_results_mmv = model_pedes.validate(results_pedes, validationData_pedestrian)
validation_results_mmv_cst = model_cst_pedes.validate(results_pedes_cst, validationData_pedestrian)


# Initialize variables to store log-likelihoods
loglike_model_mmv = 0
loglike_constant_mmv = 0
loglike_model_car = 0
loglike_constant_car = 0

# Calculate log-likelihood for the model (mmv)
for i, slide in enumerate(validation_results_mmv):
    validation_loglike = slide['Loglikelihood'].sum()
    loglike_model_mmv += validation_loglike
    print(
        f'Log likelihood for {slide.shape[0]} validation data on mmv (slide {i+1}): '
        f'{validation_loglike}'
    )

# Calculate log-likelihood for the constant model (mmv)
for i, slide in enumerate(validation_results_mmv_cst):
    validation_loglike_cst = slide['Loglikelihood'].sum()
    loglike_constant_mmv += validation_loglike_cst
    print(
        f'Log likelihood for {slide.shape[0]} validation data on mmv (constant model, slide {i+1}): '
        f'{validation_loglike_cst}'
    )

# Calculate rho-square for each slide (mmv)
for i in range(len(validation_results_mmv)):
    validation_loglike = validation_results_mmv[i]['Loglikelihood'].sum()
    validation_loglike_cst = validation_results_mmv_cst[i]['Loglikelihood'].sum()
    rho_square = 1 - (validation_loglike / validation_loglike_cst)
    print(f'Rho-square for the validation data on mmv (slide {i+1}): {rho_square}')

Log likelihood for 711 validation data on mmv (slide 1): -305.87798953822545
Log likelihood for 223 validation data on mmv (slide 2): -91.82837505388582
Log likelihood for 711 validation data on mmv (constant model, slide 1): -491.2867169242943
Log likelihood for 223 validation data on mmv (constant model, slide 2): -151.9994039479823
Rho-square for the validation data on mmv (slide 1): 0.3773941386952657
Rho-square for the validation data on mmv (slide 2): 0.39586358453542614

In [44]:


# Validate the model with the validation data for mmv
validation_results_solo_2 = model_solo_2.validate(results_solo_2, validationData_alone_2)
validation_results_solo_cst = model_cst_solo.validate(results_cst_solo, validationData_alone_2)

# Initialize variables to store log-likelihoods
loglike_model_mmv = 0
loglike_constant_mmv = 0
loglike_model_car = 0
loglike_constant_car = 0

# Calculate log-likelihood for the model (mmv)
for i, slide in enumerate(validation_results_solo_2):
    validation_loglike = slide['Loglikelihood'].sum()
    loglike_model_mmv += validation_loglike
    print(
        f'Log likelihood for {slide.shape[0]} validation data on mmv (slide {i+1}): '
        f'{validation_loglike}'
    )

# Calculate log-likelihood for the constant model (mmv)
for i, slide in enumerate(validation_results_solo_cst):
    validation_loglike_cst = slide['Loglikelihood'].sum()
    loglike_constant_mmv += validation_loglike_cst
    print(
        f'Log likelihood for {slide.shape[0]} validation data on mmv (constant model, slide {i+1}): '
        f'{validation_loglike_cst}'
    )

# Calculate rho-square for each slide (mmv)
for i in range(len(validation_results_solo_2)):
    validation_loglike = validation_results_solo_2[i]['Loglikelihood'].sum()
    validation_loglike_cst = validation_results_solo_cst[i]['Loglikelihood'].sum()
    rho_square = 1 - (validation_loglike / validation_loglike_cst)

    # Calculate rho-square for each slide (mmv
for i in range(len(validation_results_solo_2)):
    validation_loglike = validation_results_solo_2[i]['Loglikelihood'].sum()
    validation_loglike_cst = validation_results_solo_cst[i]['Loglikelihood'].sum()
    rho_square = 1 - (validation_loglike / validation_loglike_cst)
    print(f'Rho-square for the validation data on mmv (slide {i+1}): {rho_square}')

Log likelihood for 422 validation data on mmv (slide 1): -65.15025071728415
Log likelihood for 222 validation data on mmv (slide 2): -58.28145793502269
Log likelihood for 422 validation data on mmv (constant model, slide 1): -83.79744423111961
Log likelihood for 222 validation data on mmv (constant model, slide 2): -76.58265527213052
Rho-square for the validation data on mmv (slide 1): 0.22252699572083734
Rho-square for the validation data on mmv (slide 2): 0.23897313656827324